### ISSUE TITLE
Is it a good idea to use MPSSELight as Boilderplate for I2C

### ISSUE THREAD

**Issue by LwServices** [zhelnio/MPSSELight#10]
I own an FT232H and I own a couple of I2C Devices.
So far I got it running based on ftdi an411 example. this doesn't code does look alike c++ in my opinion this is not a good idea to use it as my boilerplate.
Now I found your library an i wondering if
Is it a good idea to use MPSSELight as Boilerplate for I2C?

Thank you

Lech

**Comment by zhelnio** [comment]
@LwServices  The I2C support is not implemented yet. It is not hard to add this function. So of course you can use this library, but you have to implement an I2C layer over the MPSSE by yourself
